# Libraries in python

- ## <span style="color:green"> Numpy

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

- ### <span style="color:Brown"> What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.

- #### Single Dimentional Array

- #### Multidimentional Array



In [1]:
import numpy as np
n1=np.array([10,20,30,40])
type(n1)
n1

array([10, 20, 30, 40])

In [2]:
import numpy as np
n2=np.array([[1,2,3,4,5],[5,4,3,2,1]])
n2

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [5]:
type(n2)

numpy.ndarray

In [10]:
n3=np.zeros((4,4))
n3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
type(n3)

numpy.ndarray

In [12]:
n4=np.full((3,4),99)
n4

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [13]:
n5=np.arange(10,20)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
n6=np.arange(20,50,5)
n6

array([20, 25, 30, 35, 40, 45])

In [19]:
n7=np.random.randint(1,100,10)
n7

array([73, 26, 62, 86, 80, 50, 80, 60,  6, 12])

In [6]:
n8=np.array([[5,4,3,2],[2,3,4,3]])
n8

array([[5, 4, 3, 2],
       [2, 3, 4, 3]])

In [9]:
n8.shape

(2, 4)

In [10]:
n8.shape=(4,2)
n8.shape

(4, 2)

In [22]:
n8

array([[5, 4],
       [3, 2],
       [2, 3],
       [4, 3]])

### JOINING NUMPY ARRAY
 There are three menthod of Joining Numpy Array  
- 1- vstack()
- 2- hstack()
- 3- column_stack()

In [24]:
a1=np.array([1,2,3,4,5])
a2=np.array([5,4,3,2,1])
np.vstack((a1,a2))


array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [26]:
a3=np.array([1,2,3,4,5])
a4=np.array([5,4,3,2,1])
np.hstack((a3,a4))


array([1, 2, 3, 4, 5, 5, 4, 3, 2, 1])

In [27]:
a5=np.array([1,2,3,4,5])
a6=np.array([5,4,3,2,1])
np.column_stack((a5, a6))

array([[1, 5],
       [2, 4],
       [3, 3],
       [4, 2],
       [5, 1]])

### OPERTIONS OF NUMPY
THERE ARE TWO OPERATIONS OF THE NUMPY 
- 1-  INTERSECTION
- 2-  DIFFRANCE



In [11]:
# INTERSRCTION

b1=np.array([5,6,7,8,9])
b2=np.array([1,2,3,9,5])
np.intersect1d(b1, b2)

array([5, 9])

In [30]:
# DIFFRANCE

b3=np.array([10,12,30,33,43])
b4=np.array([10,33,22,23,21])
np.setdiff1d(b3,b4)

array([12, 30, 43])

In [31]:
np.setdiff1d(b4,b3)

array([21, 22, 23])

### ADDITION OF NUMPY ARRAY 

In [32]:
c1=np.array([10,20,30])
c2=np.array([11,22,33])
np.sum([c1,c2])

126

In [33]:
np.sum([c1,c2] ,axis=0) # Coulmn Additon

array([21, 42, 63])

In [34]:
np.sum([c1,c2] ,axis=1) # Row Addition

array([60, 66])

### BASIC OPERATION

In [35]:
# BASIC ADDITION

c1=np.array([10,20,30])
c1=c1+5
c1

array([15, 25, 35])

In [36]:
c1=np.array([10,20,30])
c1=c1-5
c1

array([ 5, 15, 25])

In [37]:
c1=np.array([10,20,30])
c1=c1*2
c1

array([20, 40, 60])

In [38]:
c1=np.array([10,20,30])
c1=c1/5
c1

array([2., 4., 6.])

In [39]:
c1=np.array([20,30,40])
np.mean(c1)

30.0

In [40]:
c1=np.array([20,30,40])
np.median(c1)

30.0

In [41]:
c1=np.array([10,20,30]) # standard division
np.std(c1)

8.16496580927726

### NUMPY SAVE AND LOAD METHOD

In [42]:
b1=np.array([5,6,7,8,9])
np.save('my_array' , b1)

In [43]:
new_b1=np.load('my_array.npy')

In [44]:
new_b1

array([5, 6, 7, 8, 9])